'(("Arpeggio" "line.staff.arpeggio")
("Arpeggio down" "line.staff.arpeggio.down") 
("Arpeggio up" "line.staff.arpeggio.up")
("Glissando (straight)" "line.staff.gliss.straight")
("Glissando (wavy)" "line.staff.gliss.wavy")
("Crescendo" "line.staff.hairpin.crescendo")
("Crescendo from silence" "line.staff.hairpin.crescendo.fromsilence")
("Diminuendo" "line.staff.hairpin.diminuendo")
("Diminuendo to silence" "line.staff.hairpin.diminuendo.tosilence")
("Tie" "line.staff.tie")
("Trill" "line.staff.trill")
("Vibrato" "line.staff.vibrato")
("Wide vibrato" "line.staff.vibrato.wide")
("Pedal" "line.staff.pedal")
("Pedal lift" "line.staff.pedal.lift")
("Pedal lift again" "line.staff.pedal.lift.again")
("Pedal lift finally" "line.staff.pedal.lift.finally")
("Pedal (no line)" "line.staff.pedal.noline")
("Portamento" "line.staff.port.straight")
("Slur above" "line.staff.slur.up")
("Slur below" "line.staff.slur.down"))
